server:
    port: "SERVER_PORT"
    host: "SERVER_HOST"

database:
    url: "MONGO_URI"

auth:
    jwksUri: "JWKS_URI"

aws:
    s3:
        region: "AWS_S3_REGION"
        bucket: "AWS_S3_BUCKET"
        accessKeyId: "AWS_S3_ACCESS_KEY_ID"
        secretAccessKey: "AWS_S3_SECRET_ACCESS_KEY"

storage:
    provider: "STORAGE_PROVIDER"

broker:
    type: "BROKER_TYPE"

kafka:
    clientId: "KAFKA_CLIENT_ID"
    brokers: "KAFKA_BROKERS"
    ssl: "KAFKA_SSL"
    sasl:
        mechanism: "KAFKA_SASL_MECHANISM"
        username: "KAFKA_SASL_USERNAME"
        password: "KAFKA_SASL_PASSWORD"

cors:
    origin: "CORS_ORIGIN"
    credentials: "CORS_CREDENTIALS"
