server:
    port: 5502
    host: "localhost"

auth:
    jwksUri: "http://localhost:5501/.well-known/jwks.json"

cors:
    origin:
        - "http://localhost:3000"
        - "http://localhost:3001"
    credentials: true
